apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix
  title: Radix Open Source Portal
  description: "Your central hub for everything Radix 🚀"
  annotations:
    github.com/project-slug: equinor/radix
spec:
  type: other
  system: system:default/Radix
  lifecycle: production
  owner: team-radix
